// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Carts                     string
	CartsHistories            string
	CartsProducts             string
	CartsUsers                string
	Orders                    string
	OrdersProducts            string
	Permissions               string
	ProductCategories         string
	ProductDiscounts          string
	Products                  string
	ProductsProductCategories string
	ProductsProductDiscounts  string
	Roles                     string
	RolesPermissions          string
	SchemaMigrations          string
	Tokens                    string
	Users                     string
	UsersOrders               string
	UsersRoles                string
}{
	Carts:                     "carts",
	CartsHistories:            "carts_histories",
	CartsProducts:             "carts_products",
	CartsUsers:                "carts_users",
	Orders:                    "orders",
	OrdersProducts:            "orders_products",
	Permissions:               "permissions",
	ProductCategories:         "product_categories",
	ProductDiscounts:          "product_discounts",
	Products:                  "products",
	ProductsProductCategories: "products_product_categories",
	ProductsProductDiscounts:  "products_product_discounts",
	Roles:                     "roles",
	RolesPermissions:          "roles_permissions",
	SchemaMigrations:          "schema_migrations",
	Tokens:                    "tokens",
	Users:                     "users",
	UsersOrders:               "users_orders",
	UsersRoles:                "users_roles",
}
