version: '3'

vars:
  PROJECT_DIRECTORY:
    sh: 'pwd'

tasks:
  dk-start:
    desc: Start postgres in docker and init test DB
    cmds:
      - 'docker run --rm --name task5-test -p 5433:5432 -v {{.PROJECT_DIRECTORY}}/etc/init.sql:/docker-entrypoint-initdb.d/init.sql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=task_5 -d postgres:14.6'
  dk-stop:
    desc: Stop postgres in docker
    cmds:
      - 'docker stop task5-test'
